[package]
name = "rust_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = { version = "1.1.0", default-features = false }

[dev-dependencies]
tempfile = "3.5.0"
